In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv("Ratings.csv")
data.head()

B1  B2  B3  B4  B5
0   1   0   4   0   3
1   2   3   4   3   2
2   3   3   2   4   2
3   4   4   3   5   4
4   5   1   4   2   2

In [3]:
data.shape

(7, 5)

In [4]:
data.describe()

B1        B2        B3        B4        B5
count  7.000000  7.000000  7.000000  7.000000  7.000000
mean   3.285714  2.285714  3.142857  3.142857  3.142857
std    1.380131  1.380131  1.214986  1.772811  1.214986
min    1.000000  0.000000  1.000000  0.000000  2.000000
25%    2.500000  1.500000  2.500000  2.500000  2.000000
50%    4.000000  3.000000  4.000000  3.000000  3.000000
75%    4.000000  3.000000  4.000000  4.500000  4.000000
max    5.000000  4.000000  4.000000  5.000000  5.000000

In [5]:
from sklearn.decomposition import PCA

In [6]:
pca = PCA(random_state=42)

In [7]:
pca.fit(data)

PCA(random_state=42)

In [8]:
pca.components_

array([[-0.31118649, -0.48101502,  0.35622281, -0.69199674, -0.25696953],
       [ 0.90672615, -0.31113879,  0.25507174, -0.09225738,  0.08641369],
       [-0.12857449, -0.38163517, -0.34923551, -0.16484744,  0.82986931],
       [ 0.1452065 , -0.34290409, -0.79235694, -0.05662208, -0.47989194],
       [-0.20831306, -0.63920934,  0.24134777,  0.69444104, -0.08671783]])

In [9]:
pca.explained_variance_ratio_

array([6.51886873e-01, 1.52836342e-01, 1.30717403e-01, 6.43810220e-02,
       1.78359842e-04])

In [11]:
var_cumu = np.cumsum(pca.explained_variance_ratio_)
var_cumu

array([0.65188687, 0.80472321, 0.93544062, 0.99982164, 1.        ])